# Generated by Django 4.2.3 on 2023-07-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin_User_App", "0002_alter_user_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_super",
            field=models.BooleanField(default=False),
        ),
    ]
